name: Bug Report
description: Report a defect in the dungeon or pathfinding systems.
title: "[BUG] "
labels:
  - Bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One–two sentences describing the problem.
      placeholder: Floor flood fill starts at wrong coordinate...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Numbered steps. Keep them concise.
      placeholder: |
        1. Generate dungeon with non-square starter room
        2. Observe floor placement...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: Flood fill originates at actual room center...
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: Starts at (x,x) so fill spills into adjacent area...
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact / Why It Matters
      description: What breaks, user-visible effect, or risk if unfixed.
      placeholder: Misplaces floors causing visual gaps and incorrect path graph.
  - type: input
    id: environment
    attributes:
      label: Environment (branch / commit / Unity version)
      placeholder: master @ <short-sha>, Unity 2022.x.x
  - type: textarea
    id: suspected
    attributes:
      label: Suspected Cause / Pointers (optional)
      placeholder: Code pointer, stack trace, hypothesis...
  - type: textarea
    id: attachments
    attributes:
      label: Logs / Screenshots (optional)
      placeholder: Drag & drop or paste here.
  - type: checkboxes
    id: sanity
    attributes:
      label: Pre-Submission Checklist
      options:
        - label: I searched existing issues for duplicates
        - label: I can reproduce this reliably