name: Documentation Task
description: Improve or add project documentation / diagrams / comments
title: "[DOC] <short summary>"
labels:
  - Documentation
body:
  - type: markdown
    attributes:
      value: |
        Use for README updates, diagrams, or internal code documentation tasks.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: Add generation pipeline diagram to README.
    validations:
      required: true
  - type: textarea
    id: audience
    attributes:
      label: Audience / Scope
      placeholder: Future devs; covers DungeonDataGenerator + TileMapGenerator flow.
    validations:
      required: true
  - type: textarea
    id: outline
    attributes:
      label: Content Outline
      placeholder: |
        1. Overview
        2. Room splitting
        3. Graph creation
        4. Door BFS
        5. Tile map & bitmask
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: Source Material / References
      placeholder: File paths, external articles, class names
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - Includes diagram
        - Explains door BFS rationale
        - README updated
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: [Critical, High, Medium, Low]
      default: 3
  - type: dropdown
    id: size
    attributes:
      label: Size
      options: ["15 Mins","30 Mins","1 Hour","2 Hours","+4 Hours"]
      default: 1
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes