name: Feature Request
description: Propose a new capability or improvement.
title: "[FEATURE] "
labels:
  - Feature
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Gap
      description: What pain point or limitation are we addressing?
      placeholder: Pathfinding nodes feel jagged, no smoothing...
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: Desired Outcome
      description: What success looks like (player / system benefit).
      placeholder: Smoother movement with fewer waypoint turns...
    validations:
      required: true
  - type: textarea
    id: core_requirements
    attributes:
      label: Core Requirements
      description: Bullet list of must-haves. Use - item per line (I’ll convert to checklist manually if needed).
      placeholder: |
        - Support toggling path smoothing
        - Maintain current A* performance envelope
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Concrete pass/fail statements (Given/When/Then optional).
      placeholder: |
        - Character traverses same path with <= 20% fewer nodes
        - No collisions introduced in smoothed path
  - type: textarea
    id: notes
    attributes:
      label: Notes / References (optional)
      placeholder: Links, related issues, algorithms (e.g., funnel, string pulling)...
  - type: textarea
    id: out_of_scope
    attributes:
      label: Out of Scope (optional)
      placeholder: Not adding dynamic obstacle avoidance yet...