name: Project Issue Automation

on:
  issues:
    types: [opened, edited, labeled, unlabeled, reopened]

# Only request what you need. If you keep the project mutation, include 'projects'.
permissions:
  contents: read
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run project automation
        uses: actions/github-script@v7
        env:
          PROJECT_NUMBER: "8"
          PROJECT_OWNER: "AssassinBear23"
          DEFAULT_FEATURE_PRIORITY: "Medium"
          DEFAULT_DOC_PRIORITY: "Low"
          DEFAULT_BUG_PRIORITY: "Medium"
          SIZE_DEFAULT: "15 Mins"
        with:
          github-token: ${{ secrets.PROJECT_AUTOMATION_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = '.github/scripts/project-issue-automation.js';
            if (!fs.existsSync(path)) {
              core.setFailed(`Script not found: ${path}`);
            } else {
              const script = fs.readFileSync(path,'utf8');
              await eval(script);
            }
